parameters:
- name: Artifacts
  type: object
  default: []
- name: TestPipeline
  type: boolean
  default: false
- name: AdditionalModules
  type: object
  default: []
- name: SDKType
  type: string
  default: client
- name: ServiceDirectory
  type: string
  default: not-specified
- name: TargetDocRepoName
  type: string
  default: azure-docs-sdk-java
- name: MatrixConfigs
  type: object
  default:
    - Name: Java_ci_test_base
      Path: eng/pipelines/templates/stages/platform-matrix.json
      Selection: sparse
      NonSparseParameters: Agent
      GenerateVMJobs: true
- name: AdditionalMatrixConfigs
  type: object
  default: []
- name: MatrixFilters
  type: object
  default: []
- name: MatrixReplace
  type: object
  default: []
- name: SkipAggregateReports
  type: boolean
  default: false
- name: PreBuildSteps
  type: object
  default: []
- name: AdditionalLintingOptions
  type: string
  default: ''
- name: CITest
  type: boolean
  default: true
- name: BuildDependsOn
  type: object
  default: ''

stages:
  - stage: Build_${{ parameters.ServiceDirectory }}
    displayName: Build ${{ parameters.ServiceDirectory }}
    dependsOn: ${{ parameters.BuildDependsOn }}
    jobs:
    - template: /eng/pipelines/templates/jobs/ci.yml
      parameters:
        ServiceDirectory: ${{ parameters.ServiceDirectory }}
        SDKType: ${{ parameters.SDKType }}
        Artifacts: ${{ parameters.Artifacts }}
        AdditionalModules: ${{ parameters.AdditionalModules }}
        SkipAggregateReports: ${{ parameters.SkipAggregateReports }}
        MatrixConfigs:
          - ${{ each config in parameters.MatrixConfigs }}:
            -  ${{ config }}
          - ${{ each config in parameters.AdditionalMatrixConfigs }}:
            -  ${{ config }}
        MatrixFilters:
          - ${{ each filter in parameters.MatrixFilters }}:
            - ${{ filter }}
          # Skip TestFromSource jobs for SDKType data
          - ${{ if eq(parameters.SDKType, 'data') }}:
            - TestFromSource=^(?!true).*
        MatrixReplace:
          - ${{ each replacement in parameters.MatrixReplace }}:
            - ${{ replacement }}

          - AZURE_TEST.*=.*/
        PreBuildSteps: ${{ parameters.PreBuildSteps }}
        AdditionalLintingOptions: ${{ parameters.AdditionalLintingOptions }}
        ${{ if eq(parameters.SDKType, 'data') }}:
          TestGoals: 'verify'
          TestOptions: '-am'
        CITest: ${{ parameters.CITest }}

  - template: archetype-java-release.yml
    parameters:
      DependsOn:
        - Build_${{ parameters.ServiceDirectory }}
      ServiceDirectory: ${{ parameters.ServiceDirectory }}
      SDKType: ${{ parameters.SDKType }}
      Artifacts: ${{ parameters.Artifacts }}
      ArtifactName: packages_${{ parameters.ServiceDirectory }}
      TargetDocRepoName: ${{ parameters.TargetDocRepoName }}

